version: '3.8'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./mysql-data:/var/lib/mysql

  prisma:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - ${PRISMA_PORT}:${PRISMA_PORT}
    depends_on:
      - mysql
    environment:
      API_PORT: ${API_PORT}
    command: [ "tail", "-f", "/dev/null" ]
